title: Bear World
email: bear-world@bears.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
destination: docs
# baseurl: "" 
baseurl: "/BearWorld" 
url: "" 
facebook_username: BearWorld
twitter_username: Tweet_Bear
instagram_username: BearWorld_Pics

# Build settings
plugins:
  - jekyll-feed

exclude:
  - docs
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
